services:
  database:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: autopote
      MARIADB_USER: autopote_user
      MARIADB_PASSWORD: autopote_pwd
    volumes:
      - carole_autopote_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  carole_autopote_data:
